### ISSUE TITLE
It's a feature 

### ISSUE THREAD

**Issue by MowHogz** [eyal1izhaki/snakes-battle#38]
Traceback (most recent call last):
  File "/home/jack/Documents/snake/snakes-battle/main.py", line 165, in <module>
    main()
  File "/home/jack/Documents/snake/snakes-battle/main.py", line 39, in main
    run_game(playing_classes, ai_classes_available)
  File "/home/jack/Documents/snake/snakes-battle/main.py", line 144, in run_game
    logic.apply_logic(board, events)
  File "/home/jack/Documents/snake/snakes-battle/snakes_battle/logic.py", line 161, in apply_logic
    apply_snake_logic(board,snake)
  File "/home/jack/Documents/snake/snakes-battle/snakes_battle/logic.py", line 124, in apply_snake_logic
    snake_lost(_snake)
TypeError: snake_lost() missing 1 required positional argument: 'board'

**Comment by MowHogz** [comment]
Happened multiple times

**Comment by eyal1izhaki** [comment]
solved
